apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-app
  namespace: argocd
  resourceVersion: "2385674"
  uid: a74071a1-bce9-463c-8f75-d4d6a835713c
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: first-app
    helm:
      parameters:
      - name: pvc.storage_size
        value: 2Gi
    repoURL: https://pluhin.github.io/helm-23-23/
    targetRevision: 0.2.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
