apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
  resourceVersion: "2385676"
  uid: 973199c1-0dbe-4cbf-bac9-c31c1828d7ba
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ci-cd
    repoURL: https://github.com/pluhin/build_sa.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
